### ISSUE TITLE
app.get without res method

### ISSUE THREAD

**Issue by butera-simone** [jcubic/wayne#20]
Is there a proper way to call app.get without including a res method? Basically using the route just to execute arbitrary code. This seemed easier before the last version: now every fetch event seems to cause loading?

**Comment by jcubic** [comment]
No, this was a bug. I'm not sure how Express.js works but if you don't send anything it probably waits until timeout. At least this is what Wayne is doing wait 5 minutes and reject the promise so it shows a timeout error in the console.

I'm not sure if there is a way  to make it work, what will be the difference between:

```
app.get('/something', (req, res) => {
   setTimeout(() => {
      res.text('some text');
   }, 4 * 60 * 1000);
});
app.get('/something', (req, res) => {
   setTimeout(() => {
      some_action();
   }, 4 * 60 * 1000);
});
```

If you want to send a normal request on the route you need to do this yourself. But I can make it simpler. Maybe:
```javascript
app.get('/something', (req, res) => {
   some_action();
   res.fallback();
});
```
I don't have any other ideas for better API.

**Comment by jcubic** [comment]
I've just tested express.js and it seems that if you don't write the code for the route it just loads forever.

**Comment by butera-simone** [comment]
How would res.fallback() work? It would reject the promise?

**Comment by jcubic** [comment]
No, it would do what the old fetch did before the bug was fixed. Fetch the URL normally like there was no route.

But maybe this is something that middle where should do.

**Comment by butera-simone** [comment]
I think middleware would be good for certaing things, but I'm trying to do something that doesn't really map to common server-side functionalities. 

I want to have a path tree to serve files as pages, and another path tree to show folders inside a Solid JS component (user navigates to "/path/to/folderX" => something updates the Solid Signal => Solid launches a function that fetches the contents of folderX and re-renders the component  to show them). I get a series of advantages from this separation.

I wanted to handle the second path tree by launching a message via BroadcastChannel (without calling a res method), but if you want to mirror the Express.js API, I doubt there's any Express method that would easily fit my use case, so I'll probably need to use Wayne for serving pages, and a different router for the other path tree.

**Comment by jcubic** [comment]
You can't use Waybe that is HTTP routing librart to trigger some action, you need to use Request/Response this is how it works. why don't use use something like REST for this.

```javascript
app.get('/solid/*', (res, req) => {
   launch(res.params[0]).then(() => {
      res.json({ result: true });
   }).catch(error => {
      res.json({ result: false, error });
   });
});
```

This is the fundamental behavior of the Service Worker fetch event. You need to send response to HTTP request. The same as with express.js you can't just do an action in response to GET HTTP requests and ignore response.

If you need to do something like this, I don't think that you should use Service Worker for this.

Why don't use a normal worker and sent `postMessage('/path/to/Something');` this will have the same effect. Why are you trying to use a service Worker for this?

**Comment by jcubic** [comment]
If think that what you need to do, is ask questions about what is exactly you need and rethink what you need to use for that purpose. I don't think that Service Worker and Wayne is the solution.

**Comment by jcubic** [comment]
If you want the user to navigate to `"/path/to/folderX"` to update something, than what is exactly that you want to display? If you want a blank page you need to send the blank page, but you need to send something? Do you want a 404 error like before? Then Send 404 error. You can send an HTML file with the message that the component was updated.

You can't change the fundamental thing (HTTP protocol) to not send a response, you need to send some response.

**Comment by butera-simone** [comment]
I'm aware that this is not the original intention behind the library. I was just asking because maybe there was an option I hadn't noticed, and that would have spared me from implementing an extra router.

**Q: why don't you send something as a response?** 

A: my app has a file system composed of lightning-fs plus a collection of higher level functions I built on top of it. The user will have two different ways to navigate this file system, one sends responses with Wayne, the other one does not.

**Q: why?**

A: As I said before, there're multiple advantages in doing this. Having a Wayne-style navigation allows the user to run webapps in a separate window. But there's also the main thread, which is basically a Solid.js SPA, and includes various components. The main component is a file explorer that shows the contents of the filesystem as a desktop. This explorer latches onto the functions I built on lightning-fs, which allows the user to copy/cut/paste folders & files like a regular OS. The component gets re-rendered selectively by Solid. This SPA approach allows me to leverage the Solid ecosystem, which includes things like [this](https://github.com/Xhofe/solid-contextmenu) (extremely convenient for my project). I am also building a component that works as a P2P webRTC messenger, and that is also integrated with the rest of the OS-like interface, allowing the user to paste folders into the chat to send them to peers. As you can see, this Solid-based navigation system has to stay separated from the Wayne one, which must remain framework-agnostic to run as faithfully as possible any kind of web application.

**Q: but why do you need to mess with URLs & fetch events if that part is basically a SPA?**

A: because this way the user can go back & forth between views using the browser navigation commands, which makes it more intuitive

Hope this makes everything clear. I'll just implement an extra router (a non-service-worker one) 👍

**Comment by jcubic** [comment]
Ok, I understand why you want to want to interact with FS via pure in-browser HTTP. This was an original idea for using Service Workers for me. I'm even working on adding support for filesystems in #3.

But I still don't understand why you want to change how HTTP works and don't want the response from the HTTP requests. Note you can't change how HTTP works. And this has nothing to do with the Wayne library. This is how Service Worker works and the Web as a whole.

**Comment by butera-simone** [comment]
I don't want to "change how HTTP works". I wanna build a system of fake HTTP requests that actually just updates the components. It's pretty standard actually:

https://github.com/remix-run/react-router

https://github.com/angular-component/router

https://github.com/vuejs/router

https://github.com/solidjs/solid-router

I was just looking for a way to do it via Wayne instead of implementing an extra router

**Comment by jcubic** [comment]
So just return nothing `res.text('');` if you don't care about the response. You will get a blank page.

**Comment by jcubic** [comment]
Another note that is the router Wayne is using came from my other small library [route.js](https://github.com/jcubic/route.js), which implements just the routing without any mechanism of invocation. But I would need to update it since it's behind because it doesn't have a glob (asterisk).

**Comment by butera-simone** [comment]
But I don't need a blank page, I need the same page with a different configuration per route. That's how those routers work

**Comment by jcubic** [comment]
So you need to return the same page, you said that you don't want a response. If you have `/something/something/` route and what `/index.html` then you need to return the content of `./index.html`

**Comment by butera-simone** [comment]
But that would re-render the whole page. I'm adding the solid-js router, which re-renders only the components that need it. My solution with broadcast channels also re-rendered selectively, by sending a message to the Solid interface. But that required Wayne to include an option for not returning a response. Now I'm using Wayne for running web apps, and the solid router to handle this part, so the issue is solved as far as my app is concerned

**Comment by jcubic** [comment]
I really don't understand how you want to use HTTP for that. It looks like you don't need Service Worker at all. It seems that you need History API and not a Service Worker.

**Comment by butera-simone** [comment]
I never thought or said I needed a service worker to handle this part 🤔

I was trying to understand if there was an option to use Wayne as a generalized router that could handle Solid routing too.

One could probably implement it in HTTP with something like [a 204 code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204), but I understand it's not a priority for this library, don't worry. I was just asking in case there was a way I didn't notice.

**Comment by butera-simone** [comment]
My bad, I think there's been a misunderstanding. 

When I said I didn't want to send a response, I meant I didn't want to send content with res that would refresh the page. That's the high level behavior I was interested in. That's why I wrote "I wanna build a system of fake HTTP requests that actually just updates the components"

You were talking about the lower level concept of actual HTTP response, not the "res" object you built upon that concept. 

It's immaterial to me how the behavior is produced tbh. Whether it's an actual HTTP response (like a 204 code), or something that just mimics it (like I imagined it could be implemented in Wayne before), or something that doesn't even necessarily tries to mimic it (like the Solid router I'm using now), what's important is that I can use URLs to navigate between different configurations of components.

**Comment by jcubic** [comment]
So no, Wayne is a library to be used exclusively inside Service Worker for HTTP requests created inside the Browser, and HTTP works in a way that to HTTP requests they send HTTP response.

If you want a generic router you can use [route.js](https://github.com/jcubic/route.js). This library is just the router you can use it however you like. it's not connected to anything like Wayne is using HTTP inside Service Worker. I actually copy pasted part of that library and included it in Wayne, so I didn't have to implement the routing again, just like you want.

**Comment by butera-simone** [comment]
Btw I tried 204 with a normal service worker, if you send an undefined response with it you get to execute arbitrary code without altering the page, example:

```
self.addEventListener('fetch', event => {
    if (event.request.url.endsWith('/yo')) {
        event.respondWith(
            makeResponse()
        );
    }
});


const makeResponse = function() {
    // insert your arbitrary code here
    let y = new Response(undefined, {
        status: 204,
        headers: {
            'Content-Type': 'text/html'
        }
    });
    return y
}
```
Although this will not be tracked by the browser history, which makes it useless for my project, maybe you might wanna add it as an option to Wayne

**Comment by jcubic** [comment]
Will test it, looks interesting, but to add something like this I would need to have the use case first.

**Comment by jcubic** [comment]
So makes things clear. Do you want people to click on a link that will do nothing and execute your code? How is that different from doing your code first and then changing the URL and history?

**Comment by butera-simone** [comment]
No, 204 will not change the URL unfortunately. That's why I said that it doesn't solve my problem. What it does is it allows to execute code when a user fetches a certain URL. But the URL bar will stay the same. 

Maybe it could be used in situations in which you expect the user to alter the URL from the URL bar, and you want to give him a response in the current page instead of changing page? 

Like, you could have a browser game in which every level has a URL, like 

game/level/1
game/level/2
game/level/3

Ecc

And if the player tries to skip a level by altering the URL, you could use a 204 to launch a message to the main thread, to open a pop-up with "no cheating" XD or something like that, I don't know, I imagine there could be situations in which it could be useful,  I just mentioned in case you might find it useful for other people.

What I need to do is execute code (that updates the front end without changing the page) + altering the URL so that the user can go back and forth using the browser navigation. The Solid router does just that, unfortunately it doesn't mix well with a dynamic Posix-like file system, since its glob operator [is not recursive](https://github.com/solidjs/solid-router#nested-routes)

So I'll need to either make it recursive somehow, or find another option

**Comment by jcubic** [comment]
I've just added support for 204 response:

```javascript
app.get('/__something__', (req, res) => {
  res.text(null, { status: 204 });
});
```

both null and undefined works. But I'll wait before I publish the new version to NPM.

**Comment by butera-simone** [comment]
Let's say I have an app.get with a glob operator, like /pictures/*

The method intercepts all get requests to the subfolder "pictures", but I want the service worker to handle only those with a specific characteristic (for example: an odd number of character in req.params[0], or a request coming from a specific page); in all other instances, I want the request to be handled by the regular network. 

With a regular service worker, I'd add a fetch event listener that checks for the desired condition, and then either sends a response or does a

```
return fetch(event.request);
```

to give back control to the regular browser routine. Is there a way to do this with Wayne?

**Comment by jcubic** [comment]
Hej, did you find this out? I've got an email but I don't see your comment.

**Comment by butera-simone** [comment]
Hi, sorry, I deleted the comment for 2 reasons:

1) It was off topic, probably would have required a new issue

2) I realized my project needs too much custom stuff so I just stopped using Wayne altogether and wrote a service worker from scratch

**Comment by jcubic** [comment]
Ok. I will close this issue than. But I will think about how to add pass thru the method.

I will create another issue.

**Comment by jcubic** [comment]
It's been a while, the linked issue has been closed because you can use the pass-thru handler without any issues:

```javascript
app.get('/__something__/*', async (req, res) => {
    // arbitrary code
    const _res = await fetch(req);
    const type = _res.headers.get("Content-Type") ?? 'application/octet-stream';
    res.send(await _res.arrayBuffer(), { type });
});
```

This will just sent request to the server. So if you fetch:

```javascript
fetch('./__something__/foo.png');
```

and there is file `./__something__/foo.png` on the disk it will fetch that file.
