### ISSUE TITLE
Error retrieving binary resources

### ISSUE THREAD

**Issue by claudiosdc** [jcubic/wayne#26]
When using the FileSystem middleware and a binary resource, like an image file for example, is retrieved, the returned data is broken.

**Comment by claudiosdc** [comment]
After some investigation, I noticed that this issue is due to the fact that the FileSystem middle is not properly handling binary files. I have issued a PR (#25) to fix it.

**Comment by jcubic** [comment]
I will try to update the demo to include images and Unicode characters to see if it will work correctly.
