### ISSUE TITLE
Support ignore case sensitive when match route

### ISSUE THREAD

**Issue by jonsam-ng** [jcubic/wayne#38]
## What will be like?

```js
app.get('/message', function(req, res) {
  res.text('Lorem Ipsum');
}, { ignoreCaseSensitive: true });
```
when `ignoreCaseSensitive` param provided, we can match routes like `/message` or `/MESSAGE` that case not sensitive any more.

## Why we need this?

Sometime we want to match some requests that url case pattern not sure, but we know case not sensitive on service. So we don't
need to register paths for all different cases.

```txt
/restapi/v1/getUsers
/restapi/v1/getusers
```

**Comment by jcubic** [comment]
Do you think you need this per route? There are already options for Wayne constructor, I can add the option there. What you think?

**Comment by jonsam-ng** [comment]
I would prefer to 'ignoreCaseSensitive' per route because I'm not sure if the corresponding service is case sensitive. Registering a case-insensitive route allows me to easily respond to different styles of requests without having to register multiple times.

**Comment by jcubic** [comment]
In version 0.17.0 there is an option: `caseSensitive`:

```javascript
app.get('/message', (req, res) => {
    res.json({message: 'Hello'});
}, { caseSensitive: false });
```
