### ISSUE TITLE
WinterCG

### ISSUE THREAD

**Issue by brillout** [jcubic/wayne#5]
Curious; is supporting https://wintercg.org/ something you are interested in?

(CC @cyco130 author of [HatTip](https://github.com/hattipjs/hattip) which is also a modern cross-platform Express.js alternative.)

**Comment by jcubic** [comment]
Wayne is not cross-platform it's a Browser only library. If you need to support server-side you have express.js, it doesn't make much sense to compete with express which works well.

**Comment by brillout** [comment]
Ah, I see, interesting. I wonder what the use cases are? Frameworks like Express.js exist to transfer information that only exists on the server-side (database) to the user's client.

**Comment by jcubic** [comment]
The library is like express.js because it have similar API, but not on the server only for Service Worker. You can have the same what express.js does but in the browser.

**Comment by jcubic** [comment]
The use case would be if you want to have files in a browser that work like normal files (or API requests) but are created in the browser.

An example use case is when you want for instance change API from REST to GraphQL and you write Facade in Service Worker and you don't need to change the application.

I use the same technique when I save files in indexedDB (with a library) and serve them as static files.
